# Generated by Django 3.2 on 2021-05-06 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0002_auto_20210506_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
