# Generated by Django 3.2 on 2021-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0004_auto_20210506_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
