# Generated by Django 3.2 on 2021-05-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0007_auto_20210506_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/pics/'),
        ),
    ]
