# Generated by Django 3.2 on 2021-05-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0008_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile/pics/'),
        ),
    ]
