# Generated by Django 3.2 on 2021-05-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0012_auto_20210507_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
