# Generated by Django 3.2 on 2021-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0014_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile/pics/'),
        ),
    ]
