# Generated by Django 3.2 on 2021-05-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0015_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
